import type { Data } from "./plan-store";

// Images live in the same KV namespace as the data blob, one key per image at
// `img:<uuid>`, with the bytes as the value and the content type in metadata.
// (R2 would be the natural home, but enabling it requires a billing
// subscription on the account even at zero cost; KV needs none and its 25MB
// value ceiling is far above what an entry image will ever be.)
//
// The blob itself only ever stores the uuid — it is re-PUT in full on every
// save, so bytes can never go in it.
export const IMG_PREFIX = "img:";
export const MAX_IMAGE_BYTES = 10 * 1024 * 1024;
export const ALLOWED_TYPES = new Set([
  "image/webp", "image/png", "image/jpeg", "image/gif", "image/avif",
]);

export interface ImageMeta { ct: string; at: number }

// Ids are generated by crypto.randomUUID(); anything else is rejected before it
// reaches KV so a crafted id can't address a key outside the img: prefix —
// `auth:secret` lives in this same namespace.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
export const isImageId = (id: string): boolean => UUID_RE.test(id);
export const imageKey = (id: string): string => IMG_PREFIX + id;

// An upload lands in KV before the save that references it, so there is always
// a window in which a live image looks like garbage — and it stretches as far
// as the save can be delayed, which is unbounded if the client goes offline
// holding a pending write.
//
// The grace is deliberately far longer than that window needs to be. Sweeping
// is only the backstop for genuinely abandoned uploads, which are rare, so
// collecting one a day late costs nothing — while sweeping too eagerly would
// delete an image whose reference was merely in transit, which is unrecoverable
// and exactly the failure this whole design exists to prevent.
const SWEEP_GRACE_MS = 24 * 60 * 60 * 1000;
const SWEEP_INTERVAL_MS = 10 * 60 * 1000;
const SWEEP_KEY = "sweep:at";

// How long after upload a client may still disown its own image (see the DELETE
// route). Long enough for a slow upload to finish and be abandoned, short
// enough that the endpoint can't be pointed at an established image.
export const DISOWN_WINDOW_MS = 60 * 60 * 1000;

/** Every image id referenced anywhere in the blob. */
export function imageRefs(data: Data): Set<string> {
  const refs = new Set<string>();
  if (!Array.isArray(data?.plans)) return refs;
  for (const plan of data.plans) {
    if (!Array.isArray(plan?.lists)) continue;
    for (const list of plan.lists) {
      if (!Array.isArray(list?.entries)) continue;
      for (const entry of list.entries) {
        if (typeof entry?.image === "string" && entry.image) refs.add(entry.image);
      }
    }
  }
  return refs;
}

/**
 * Delete the images that `next` drops relative to `current`.
 *
 * This is the primary no-orphan mechanism: every way an image can stop being
 * referenced — detach, entry/list/plan delete, undo, overwriting an entry's
 * image — reaches the server as one blob replacing another, so the set
 * difference catches all of them without the client having to ask.
 *
 * Call it only *after* the new blob is committed. Deleting first would leave a
 * reference pointing at nothing if the write then failed, which is worse than
 * an orphan: an orphan is invisible and the sweep collects it, a dangling
 * reference is a broken image on screen.
 */
export async function reconcile(kv: KVNamespace, current: Data, next: Data): Promise<void> {
  const keep = imageRefs(next);
  const dead = [...imageRefs(current)].filter((id) => !keep.has(id) && isImageId(id));
  await Promise.all(dead.map((id) => kv.delete(imageKey(id))));
}

/**
 * Full reconciliation against the live blob: delete every stored image that
 * nothing references.
 *
 * `reconcile` covers state *transitions*, but an image can become unreferenced
 * without one — the upload succeeds and then the tab closes, or the save that
 * would have carried the reference loses a 409 to another device. In both the
 * id never appears in any blob, so no diff can see it. This is the backstop for
 * exactly those windows.
 *
 * Throttled via KV and skipped for young keys, so it costs one list per ten
 * minutes at most and can never race an upload that is still in flight.
 */
export async function sweep(kv: KVNamespace, data: Data): Promise<void> {
  const now = Date.now();
  const last = Number((await kv.get(SWEEP_KEY)) || 0);
  if (now - last < SWEEP_INTERVAL_MS) return;
  await kv.put(SWEEP_KEY, String(now));

  const keep = imageRefs(data);
  const dead: string[] = [];
  let cursor: string | undefined;
  for (;;) {
    const page = await kv.list<ImageMeta>({ prefix: IMG_PREFIX, cursor });
    for (const key of page.keys) {
      const id = key.name.slice(IMG_PREFIX.length);
      if (keep.has(id)) continue;
      if (now - (key.metadata?.at ?? 0) < SWEEP_GRACE_MS) continue; // still in flight
      dead.push(key.name);
    }
    if (page.list_complete) break;
    cursor = page.cursor;
  }
  await Promise.all(dead.map((name) => kv.delete(name)));
}
