import type { Data } from "./plan-store";

// R2 layout: one object per image at `img/<uuid>`. The data blob only ever
// stores the uuid (Entry.image), never bytes — the blob is re-PUT in full on
// every save, so it has to stay tiny.
export const IMG_PREFIX = "img/";
export const MAX_IMAGE_BYTES = 10 * 1024 * 1024;
export const ALLOWED_TYPES = new Set([
  "image/webp", "image/png", "image/jpeg", "image/gif", "image/avif",
]);

// Ids are generated by crypto.randomUUID(); anything else is rejected before it
// reaches R2 so a crafted id can't address an object outside the img/ prefix.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
export const isImageId = (id: string): boolean => UUID_RE.test(id);
export const imageKey = (id: string): string => IMG_PREFIX + id;

// An upload lands in R2 before the save that references it. The sweep must not
// mistake that in-flight object for garbage, so anything younger than this is
// left alone — the reference has seconds to arrive, not minutes.
const SWEEP_GRACE_MS = 15 * 60 * 1000;
const SWEEP_INTERVAL_MS = 10 * 60 * 1000;
const SWEEP_KEY = "sweep:at";

/** Every image id referenced anywhere in the blob. */
export function imageRefs(data: Data): Set<string> {
  const refs = new Set<string>();
  if (!Array.isArray(data?.plans)) return refs;
  for (const plan of data.plans) {
    if (!Array.isArray(plan?.lists)) continue;
    for (const list of plan.lists) {
      if (!Array.isArray(list?.entries)) continue;
      for (const entry of list.entries) {
        if (typeof entry?.image === "string" && entry.image) refs.add(entry.image);
      }
    }
  }
  return refs;
}

/**
 * Strip references to objects that aren't in R2, mutating `next` in place.
 *
 * The mirror of an orphan, and just as unwanted: a reference with no object
 * renders as a broken image forever. Only ids that `current` didn't already
 * carry are checked, so a normal save does no extra work and a save that
 * attaches an image does exactly one head request.
 */
export async function dropMissingRefs(bucket: R2Bucket, current: Data, next: Data): Promise<void> {
  const known = imageRefs(current);
  const added = [...imageRefs(next)].filter((id) => !known.has(id));
  if (!added.length) return;
  const missing = new Set<string>();
  await Promise.all(added.map(async (id) => {
    if (!isImageId(id) || !(await bucket.head(imageKey(id)))) missing.add(id);
  }));
  if (!missing.size) return;
  for (const plan of next.plans) {
    for (const list of plan.lists ?? []) {
      for (const entry of list.entries ?? []) {
        if (entry.image && missing.has(entry.image)) delete entry.image;
      }
    }
  }
}

/**
 * Delete the objects that `next` drops relative to `current`.
 *
 * This is the primary no-orphan mechanism: every way an image can stop being
 * referenced — detach, entry/list/plan delete, undo, overwriting an entry's
 * image — reaches the server as one blob replacing another, so the set
 * difference catches all of them without the client having to ask.
 *
 * Call it only *after* the new blob is committed. Deleting first would leave a
 * reference pointing at nothing if the write then failed, which is worse than
 * an orphan: an orphan is invisible and the sweep collects it, a dangling
 * reference is a broken image on screen.
 */
export async function reconcile(bucket: R2Bucket, current: Data, next: Data): Promise<void> {
  const keep = imageRefs(next);
  const dead = [...imageRefs(current)].filter((id) => !keep.has(id) && isImageId(id));
  if (dead.length) await bucket.delete(dead.map(imageKey));
}

/**
 * Full reconciliation against the live blob: delete every stored object that
 * nothing references.
 *
 * `reconcile` covers state *transitions*, but an object can become unreferenced
 * without one — the upload succeeds and then the tab closes, or the save that
 * would have carried the reference loses a 409 to another device. In both the
 * id never appears in any blob, so no diff can see it. This is the backstop for
 * exactly those windows.
 *
 * Throttled via KV and skipped for young objects, so it costs one R2 list per
 * ten minutes at most and can never race an upload that is still in flight.
 */
export async function sweep(kv: KVNamespace, bucket: R2Bucket, data: Data): Promise<void> {
  const now = Date.now();
  const last = Number((await kv.get(SWEEP_KEY)) || 0);
  if (now - last < SWEEP_INTERVAL_MS) return;
  await kv.put(SWEEP_KEY, String(now));

  const keep = imageRefs(data);
  const dead: string[] = [];
  let cursor: string | undefined;
  do {
    const page = await bucket.list({ prefix: IMG_PREFIX, cursor });
    for (const obj of page.objects) {
      const id = obj.key.slice(IMG_PREFIX.length);
      if (keep.has(id)) continue;
      if (now - obj.uploaded.getTime() < SWEEP_GRACE_MS) continue; // still in flight
      dead.push(obj.key);
    }
    cursor = page.truncated ? page.cursor : undefined;
  } while (cursor);

  // delete() takes at most 1000 keys per call.
  for (let i = 0; i < dead.length; i += 1000) await bucket.delete(dead.slice(i, i + 1000));
}
